### FAIL - validInput false dni
POST http://dev-vacunacion-sanjuan.sisanjuan.gob.ar/index.php?option=com_ajax&plugin=xtwssipe&format=json
content-type: application/json

{
    "dni": "177241a",
    "sexo": "F",
    "tramiteNro": "222261631"
}

### FAIL - validInput false sexo
POST http://dev-vacunacion-sanjuan.sisanjuan.gob.ar/index.php?option=com_ajax&plugin=xtwssipe&format=json
content-type: application/json

{
    "dni": "1772416",
    "sexo": "T",
    "tramiteNro": "222261631"
}

### FAIL - validInput false tramiteNro
POST http://dev-vacunacion-sanjuan.sisanjuan.gob.ar/index.php?option=com_ajax&plugin=xtwssipe&format=json
content-type: application/json

{
    "dni": "1772416",
    "sexo": "M",
    "tramiteNro": "22226163a"
}


### OK - Consulta DNI Correcto y San Juan
POST http://dev-vacunacion-sanjuan.sisanjuan.gob.ar/index.php?option=com_ajax&plugin=xtwssipe&format=json
content-type: application/json

{
    "dni": "1772416",
    "sexo": "F",
    "tramiteNro": "222261631"
}

### OK - Consulta DNI Correcto con 0, San Juan y tramite con 00
POST http://dev-vacunacion-sanjuan.sisanjuan.gob.ar/index.php?option=com_ajax&plugin=xtwssipe&format=json
content-type: application/json

{
    "dni": "01772416",
    "sexo": "F",
    "tramiteNro": "00222261631"
}


### FAIL - Consulta DNI Correcto con 0, San Juan, tramite con 00 y Sexo Incorrecto
POST http://dev-vacunacion-sanjuan.sisanjuan.gob.ar/index.php?option=com_ajax&plugin=xtwssipe&format=json
content-type: application/json

{
    "dni": "01772416",
    "sexo": "M",
    "tramiteNro": "00222261631"
}

### FAIL - Consulta DNI Incorrecto
POST http://dev-vacunacion-sanjuan.sisanjuan.gob.ar/index.php?option=com_ajax&plugin=xtwssipe&format=json
content-type: application/json

{
    "dni": "00000000",
    "sexo": "F",
    "tramiteNro": "222261631"
}

### FAIL - Check Consulta DNI Correcto, tramite con 00 y No San Juan
POST http://dev-vacunacion-sanjuan.sisanjuan.gob.ar/index.php?option=com_ajax&plugin=xtwssipe&format=json
content-type: application/json

{
    "dni": "22269197",
    "sexo": "M",
    "tramiteNro": "00173558151"
}

### FAIL - Check Consulta OK, tramite incorrecto
POST http://dev-vacunacion-sanjuan.sisanjuan.gob.ar/index.php?option=com_ajax&plugin=xtwssipe&format=json
content-type: application/json

{
    "dni": "01772416",
    "sexo": "F",
    "tramiteNro": "00222261999"
}

